version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: otus_local
      POSTGRES_USER: otus_local
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: