apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: "otus_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password_456"
  POSTGRES_HOST: "my-release-postgresql"
  POSTGRES_PORT: "5432"